(() => {
'use strict';
const $=s=>document.querySelector(s); let map=null,layer=null,userMarker=null;
  async function ensureLeaflet(){if(window.L)return window.L;if(!document.querySelector('link[data-dz407-leaflet]')){const l=document.createElement('link');l.rel='stylesheet';l.href='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css';l.dataset.dz407Leaflet='1';document.head.appendChild(l);}return await new Promise((resolve,reject)=>{const old=document.querySelector('script[data-dz407-leaflet]');if(old){old.addEventListener('load',()=>resolve(window.L),{once:true});old.addEventListener('error',reject,{once:true});return;}const s=document.createElement('script');s.src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js';s.async=true;s.dataset.dz407Leaflet='1';s.onload=()=>resolve(window.L);s.onerror=reject;document.head.appendChild(s);});}
  function stopCoords(row){
    if(Number.isFinite(Number(row?.lat))&&Number.isFinite(Number(row?.lon)))return {lat:Number(row.lat),lon:Number(row.lon),name:row.stopName||row.route};
    const m=row.operator==='KMB'?state.kmbStops:row.operator==='CTB'?state.ctbStops:row.operator==='GMB'?state.gmbStops:null;if(!m)return null;const s=m.get(String(row.stopId));if(!s)return null;const lat=Number(s.lat??s.latitude),lon=Number(s.long??s.lng??s.longitude);return Number.isFinite(lat)&&Number.isFinite(lon)?{lat,lon,name:s.name_tc||row.stopName||row.route}:null;
  }
  function ensureHost(){let host=$('#dz407Map');if(host)return host;host=document.createElement('section');host.id='dz407Map';host.className='dz407-map hidden';host.innerHTML='<div id="dz407MapCanvas"></div>';$('#nearbySection')?.appendChild(host);return host;}
  async function showMap(){const host=ensureHost(),btn=$('#dz407MapBtn');if(!host)return;if(!host.classList.contains('hidden')){host.classList.add('hidden');if(btn)btn.textContent='地圖';return;}if(btn){btn.disabled=true;btn.textContent='地圖載入中…';}try{const L=await ensureLeaflet();const pos=await new Promise((resolve,reject)=>navigator.geolocation.getCurrentPosition(p=>resolve({lat:p.coords.latitude,lon:p.coords.longitude}),reject,{enableHighAccuracy:true,maximumAge:8000,timeout:12000}));host.classList.remove('hidden');if(!map){map=L.map($('#dz407MapCanvas'),{zoomControl:true});L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);layer=L.layerGroup().addTo(map);}else layer.clearLayers();if(userMarker)map.removeLayer(userMarker);userMarker=L.marker([pos.lat,pos.lon]).addTo(map).bindTooltip('你的位置');const pts=[[pos.lat,pos.lon]];for(const r of (state.nearby||[]).slice(0,24)){const c=stopCoords(r);if(!c)continue;pts.push([c.lat,c.lon]);L.marker([c.lat,c.lon]).addTo(layer).bindTooltip(`${r.route} · ${c.name}`);}if(pts.length>1)map.fitBounds(pts,{padding:[20,20],maxZoom:18});else map.setView([pos.lat,pos.lon],17);setTimeout(()=>map.invalidateSize(),80);if(btn)btn.textContent='收起地圖';}catch{if(btn)btn.textContent='地圖';}finally{if(btn)btn.disabled=false;}}


const btn=document.createElement('button');btn.id='dz407MapBtn';btn.type='button';btn.className='filter';btn.textContent='地圖';$('.nearby-panel').appendChild(btn);btn.addEventListener('click',showMap);
const style=document.createElement('style');style.textContent='#dz407MapCanvas{height:280px;width:100%}.dz407-map{margin-top:12px}';document.head.appendChild(style);
})();