(() => {
  "use strict";
  const DATA_URL="./data/route-timetables.json",SERVICE_META_URL="./service-calendars.json",DETAIL_STORAGE_KEY="daozhan_route_timetables_v1",SERVICE_STORAGE_KEY="daozhan_service_windows_v1";
  const dayLabels={weekday:"星期一至五",saturday:"星期六",sunday_public_holiday:"星期日及公眾假期"};
  const official={KMB:r=>`https://search.kmb.hk/KMBWebSite/?action=routesearch&route=${encodeURIComponent(r)}`,CTB:r=>`https://mobile.citybus.com.hk/nwp3/?f=1&ds=${encodeURIComponent(r)}`,MTRB:()=>"https://www.mtr.com.hk/ch/customer/services/searchBusRouteDetails.php"};
  let databasePromise,serviceDataPromise;
  const validDatabase=v=>v&&v.schemaVersion===1&&Array.isArray(v.records)&&v.records.every(r=>r?.operator&&r?.route&&r?.bound&&r?.days);
  const validServiceData=v=>v&&v.meta&&v.windows&&v.calendars&&typeof v.windows==="object"&&typeof v.calendars==="object";
  function readStored(key,validator){try{const value=JSON.parse(localStorage.getItem(key)||"null");return validator(value)?value:null;}catch(_){return null;}}
  function store(key,value){try{localStorage.setItem(key,JSON.stringify(value));}catch(_){}}
  async function fetchJSON(url){const response=await fetch(url,{cache:"no-cache"});if(!response.ok)throw new Error(`HTTP ${response.status}`);return response.json();}
  async function loadDatabase(){if(databasePromise)return databasePromise;databasePromise=(async()=>{const lastGood=readStored(DETAIL_STORAGE_KEY,validDatabase);try{const fresh=await fetchJSON(DATA_URL);if(!validDatabase(fresh))throw new Error("invalid timetable database");store(DETAIL_STORAGE_KEY,fresh);return{value:fresh,stale:false};}catch(error){return{value:lastGood||{schemaVersion:1,records:[]},stale:true,error};}})();return databasePromise;}
  async function loadServiceData(){if(serviceDataPromise)return serviceDataPromise;serviceDataPromise=(async()=>{const lastGood=readStored(SERVICE_STORAGE_KEY,validServiceData);try{const meta=await fetchJSON(SERVICE_META_URL),calendarCount=Number(meta.calendarShards)||0,windowCount=Number(meta.shards)||0;if(!calendarCount||!windowCount)throw new Error("invalid service metadata");const[calendarParts,windowParts]=await Promise.all([Promise.all(Array.from({length:calendarCount},(_,i)=>fetchJSON(`./service-calendars-${i}.json`))),Promise.all(Array.from({length:windowCount},(_,i)=>fetchJSON(`./service-windows-${i}.json`)))]);const fresh={meta,calendars:Object.assign({},...calendarParts),windows:Object.assign({},...windowParts)};if(!validServiceData(fresh))throw new Error("invalid service windows");store(SERVICE_STORAGE_KEY,fresh);return{value:fresh,stale:false};}catch(error){return{value:lastGood||{meta:{},calendars:{},windows:{}},stale:true,error};}})();return serviceDataPromise;}
  const operatorOf=route=>route.operator==="MTR"?"MTRB":route.operator,upper=value=>String(value||"").trim().toUpperCase();
  function normalizedPlace(value){return String(value||"").normalize("NFKC").toUpperCase().replace(/[\s（）()－—–,，.。·・/／]+/g,"").replace(/巴士總站|公共運輸交匯處|總站/g,"站");}
  function endpointsConfirm(record,route){return Boolean(record?.origin&&record?.destination&&route?.orig&&route?.dest&&normalizedPlace(record.origin)===normalizedPlace(route.orig)&&normalizedPlace(record.destination)===normalizedPlace(route.dest));}
  function detailedMatch(records,route){const operator=operatorOf(route),routeNo=upper(route.route),bound=upper(route.bound||"O"),serviceType=String(route.serviceType||"1"),sameRoute=(records||[]).filter(r=>r.operator===operator&&upper(r.route)===routeNo);const exact=sameRoute.find(r=>upper(r.bound)===bound&&String(r.serviceType||"1")===serviceType);if(exact)return{record:exact,match:"exact"};const boundOnly=sameRoute.find(r=>upper(r.bound)===bound);if(boundOnly)return{record:boundOnly,match:"bound"};const endpoint=sameRoute.find(r=>endpointsConfirm(r,route));return endpoint?{record:endpoint,match:"endpoints"}:{record:null,match:null,candidates:sameRoute};}
  const findRecord=(records,route)=>detailedMatch(records,route).record;
  function serviceWindowMatch(windows,route){const operator=operatorOf(route),routeNo=upper(route.route),bound=upper(route.bound||"O"),key=`${operator}|${routeNo}|${bound}`;if(windows?.[key])return{key,value:windows[key],match:"bound"};return{key,value:null,match:null,candidates:Object.keys(windows||{}).filter(k=>k.startsWith(`${operator}|${routeNo}|`))};}
  function calendarRuns(calendar,bucket){const days=Array.isArray(calendar?.d)?calendar.d:[];return bucket==="weekday"?days.slice(0,5).some(Boolean):bucket==="saturday"?Boolean(days[5]):Boolean(days[6])||Boolean(calendar?.a?.length);}
  function normalizedWindow(pair){if(!Array.isArray(pair)||pair.length<2)return null;const first=Number(pair[0]),rawLast=Number(pair[1]);if(!Number.isFinite(first)||!Number.isFinite(rawLast))return null;return[first,rawLast<first?rawLast+1440:rawLast];}
  function basicDays(serviceWindows,calendars){const result={};for(const bucket of Object.keys(dayLabels)){const ranges=Object.entries(serviceWindows||{}).filter(([serviceId])=>calendarRuns(calendars?.[serviceId],bucket)).map(([,pair])=>normalizedWindow(pair)).filter(Boolean);result[bucket]=ranges.length?{first:Math.min(...ranges.map(x=>x[0])),last:Math.max(...ranges.map(x=>x[1]))}:{noService:true};}return result;}
  function formatMinutes(value){const minutes=Number(value);if(!Number.isFinite(minutes))return"—";const day=Math.floor(minutes/1440),clock=((minutes%1440)+1440)%1440,text=`${String(Math.floor(clock/60)).padStart(2,"0")}:${String(clock%60).padStart(2,"0")}`;return day>0?`翌日 ${text}`:text;}
  function clockMinutes(value){const match=String(value||"").match(/^(\d{1,2}):(\d{2})$/);return match?Number(match[1])*60+Number(match[2]):null;}
  function detailedClock(value,reference){const current=clockMinutes(value),base=clockMinutes(reference);return current!=null&&base!=null&&current<base?`翌日 ${value}`:value;}
  function renderDay(day,service){if(!service||service.noService)return`<div class="timetable-day"><h4>${dayLabels[day]}</h4><p class="timetable-empty">不設服務</p></div>`;const departures=Array.isArray(service.departures)?service.departures:[];if(departures.length)return`<div class="timetable-day"><h4>${dayLabels[day]}</h4><div class="timetable-departures">${departures.map(x=>`<time>${escapeHtml(x)}</time>`).join("")}</div></div>`;const periods=Array.isArray(service.periods)?service.periods:[],first=service.first||periods[0]?.start||"—",last=service.last||periods.at(-1)?.end||"—";return`<div class="timetable-day"><h4>${dayLabels[day]}</h4><div class="timetable-first-last"><span>首班 <strong>${escapeHtml(first)}</strong></span><span>尾班 <strong>${escapeHtml(detailedClock(last,first))}</strong></span></div>${periods.map(p=>`<div class="timetable-period"><span>${escapeHtml(p.start)}–${escapeHtml(detailedClock(p.end,p.start))}</span><strong>${escapeHtml(p.headway)} 分鐘</strong></div>`).join("")}</div>`;}
  function renderRecord(record,stale){const source=record.source||{};return`<details class="route-timetable" open><summary>總站開車時間</summary><div class="timetable-tier">詳細官方時間表</div><div class="timetable-grid">${Object.keys(dayLabels).map(day=>renderDay(day,record.days[day])).join("")}</div><div class="timetable-meta">${stale?'<span class="timetable-stale">目前使用上次有效版本</span>':""}<span>生效：${escapeHtml(source.effectiveDate||"官方頁面未列明")}</span><span>最後核實：${escapeHtml(source.lastVerified||"—")}</span>${source.url?`<a href="${escapeHtml(source.url)}" target="_blank" rel="noopener noreferrer">官方來源 ↗</a>`:""}</div></details>`;}
  function renderBasic(route,days,stale,generated){const operator=operatorOf(route),source=(official[operator]||(()=>"https://data.gov.hk/"))(route.route),dayHtml=Object.keys(dayLabels).map(day=>{const service=days[day];if(!service||service.noService)return`<div class="timetable-day"><h4>${dayLabels[day]}</h4><p class="timetable-empty">不設服務／資料未列明</p></div>`;return`<div class="timetable-day"><h4>${dayLabels[day]}</h4><div class="timetable-first-last"><span>首班 <strong>${escapeHtml(formatMinutes(service.first))}</strong></span><span>尾班 <strong>${escapeHtml(formatMinutes(service.last))}</strong></span></div><p class="timetable-headway-unavailable">班次間隔暫未提供</p></div>`;}).join(""),verified=generated?String(generated).slice(0,10):"—";return`<details class="route-timetable timetable-basic" open><summary>總站開車時間</summary><div class="timetable-tier">基本服務時間</div><div class="timetable-grid">${dayHtml}</div><div class="timetable-meta">${stale?'<span class="timetable-stale">目前使用上次有效版本</span>':""}<span>資料更新：${escapeHtml(verified)}</span><a href="${escapeHtml(source)}" target="_blank" rel="noopener noreferrer">官方時間表 ↗</a></div></details>`;}
  function officialLink(route){return(official[operatorOf(route)]||(()=>"https://data.gov.hk/"))(route.route);}
  function renderMissing(route){return`<div class="route-next-arrival route-service"><small>服務時間／總站開車</small><strong>時間表暫未收錄</strong><a class="timetable-official-link" href="${escapeHtml(officialLink(route))}" target="_blank" rel="noopener noreferrer">查看官方時間表 ↗</a></div>`;}
  function diagnoseMatch(route,records,windows){const detail=detailedMatch(records,route),basic=serviceWindowMatch(windows,route);return{route:`${operatorOf(route)}|${upper(route.route)}|${upper(route.bound||"O")}|${route.serviceType||"1"}`,detailMatch:detail.match,basicMatch:basic.match,detailCandidates:(detail.candidates||[]).map(r=>`${r.bound}|${r.serviceType||"1"}`),basicCandidates:basic.candidates||[]};}
  const placeholder=()=>'<div class="route-next-arrival route-service" data-route-timetable><small>服務時間／總站開車</small><strong>時間表載入中…</strong></div>';
  async function render(route,target){if(!target)return;const[detailResult,serviceResult]=await Promise.all([loadDatabase(),loadServiceData()]),detail=detailedMatch(detailResult.value.records,route);if(detail.record){target.innerHTML=renderRecord(detail.record,detailResult.stale);return;}const basic=serviceWindowMatch(serviceResult.value.windows,route);if(basic.value){target.innerHTML=renderBasic(route,basicDays(basic.value,serviceResult.value.calendars),serviceResult.stale,serviceResult.value.meta.generated);return;}const diagnostic=diagnoseMatch(route,detailResult.value.records,serviceResult.value.windows);if(diagnostic.detailCandidates.length||diagnostic.basicCandidates.length)console.warn("[到站時間表] 資料存在但配對失敗",diagnostic);target.innerHTML=renderMissing(route);}
  function resetForTests(){databasePromise=null;serviceDataPromise=null;}
  window.dzTimetable={loadDatabase,loadServiceData,render,placeholder,findRecord,renderRecord,renderBasic,renderMissing,detailedMatch,serviceWindowMatch,basicDays,formatMinutes,diagnoseMatch,_resetForTests:resetForTests};
})();
