const KMB_API="https://data.etabus.gov.hk/v1/transport/kmb";
const CTB_API="https://rt.data.gov.hk/v2/transport/citybus";
const GMB_API="https://data.etagmb.gov.hk";
const $=s=>document.querySelector(s);
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const favorites=()=>{try{return JSON.parse(localStorage.getItem("daozhan_favorites_v2")||"[]")}catch{return[]}};
const opName=op=>op==="CTB"?"城巴":op==="GMB"?"小巴":"九巴";
const etaMinutes=iso=>Math.max(0,Math.round((new Date(iso)-Date.now())/60000));
const etaLabel=iso=>{if(!iso)return"未有預報";const m=etaMinutes(iso);return m===0?"即將到站":`${m} 分鐘`};
async function getJSON(url){const r=await fetch(url,{headers:{Accept:"application/json"}});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}
async function getFavEtas(f){let rows=[];if(f.operator==="KMB"){const j=await getJSON(`${KMB_API}/eta/${encodeURIComponent(f.stopId)}/${encodeURIComponent(f.route)}/${encodeURIComponent(f.serviceType)}`);rows=(j.data||[]).filter(x=>!x.dir||x.dir===f.bound)}else if(f.operator==="CTB"){const j=await getJSON(`${CTB_API}/eta/ctb/${encodeURIComponent(f.stopId)}/${encodeURIComponent(f.route)}`);rows=(j.data||[]).filter(x=>!x.dir||x.dir===f.bound)}else{const j=await getJSON(`${GMB_API}/eta/route-stop/${encodeURIComponent(f.routeId)}/${encodeURIComponent(f.routeSeq||f.serviceType)}/${encodeURIComponent(f.stopSeq)}`);rows=(j.data?.eta||[]).map(x=>({eta:x.timestamp,rmk_tc:x.remarks_tc||""}))}return rows.filter(x=>x.eta&&new Date(x.eta)>=Date.now()-60000).sort((a,b)=>new Date(a.eta)-new Date(b.eta)).slice(0,3)}
async function renderFavs(){const fs=favorites();const box=$("#favList");if(!fs.length){box.innerHTML='<div class="muted">未有收藏。先喺手機版《到站》收藏常搭路線。</div>';return}box.innerHTML=fs.map((f,i)=>`<button class="fav-card" data-fav="${i}"><div class="fav-top"><span class="route">${esc(f.route)}</span><span class="operator">${opName(f.operator)}</span></div><div class="eta-main" data-main="${i}">更新 ETA…</div><div class="eta-more" data-more="${i}"></div><div class="stop">${esc(f.stopName)} → ${esc(f.destination)}</div></button>`).join("");fs.forEach(async(f,i)=>{try{const etas=await getFavEtas(f);const main=$(`[data-main="${i}"]`),more=$(`[data-more="${i}"]`);if(!main)return;main.textContent=etas[0]?etaLabel(etas[0].eta):"未有預報";more.textContent=etas.slice(1).map(x=>etaLabel(x.eta)).join(" · ")}catch{const main=$(`[data-main="${i}"]`);if(main)main.textContent="暫時未能更新"}});document.querySelectorAll("[data-fav]").forEach(b=>b.onclick=()=>showFavorite(fs[Number(b.dataset.fav)]))}
async function showFavorite(f){$("#favSection").classList.add("hidden");$("#searchSection").classList.add("hidden");$("#openSearch").classList.add("hidden");$("#detailSection").classList.remove("hidden");$("#detail").innerHTML='<div class="muted">更新 ETA…</div>';try{const etas=await getFavEtas(f);$("#detail").innerHTML=`<div class="detail-card"><div class="detail-title"><span class="route">${esc(f.route)}</span><span class="operator">${opName(f.operator)}</span></div><div class="detail-eta">${etas[0]?etaLabel(etas[0].eta):"未有預報"}</div><div class="stop">${esc(f.stopName)} → ${esc(f.destination)}</div><div class="detail-list">${etas.slice(1).map((e,i)=>`<div>第 ${i+2} 班 · <strong>${esc(etaLabel(e.eta))}</strong></div>`).join("")||'<div>未有其他預報</div>'}</div></div>`}catch{$("#detail").innerHTML='<div class="error">暫時未能取得 ETA。</div>'}}
let routes=[];async function loadRoutes(){try{const [k,c]=await Promise.all([getJSON("../kmb-routes.json"),getJSON("../ctb-routes.json")]);routes=[...(k.data||[]).map(r=>({operator:"KMB",route:r.route,orig:r.orig_tc,dest:r.dest_tc,bound:r.bound,serviceType:r.service_type})),...(c.data||[]).flatMap(r=>[{operator:"CTB",route:r.route,orig:r.orig_tc,dest:r.dest_tc,bound:"O",serviceType:"1"},{operator:"CTB",route:r.route,orig:r.dest_tc,dest:r.orig_tc,bound:"I",serviceType:"1"}])]}catch{routes=[]}}
function doSearch(){const q=$("#searchInput").value.trim().toUpperCase();if(!q){$("#searchResults").innerHTML="";return}const rank={KMB:0,CTB:1,GMB:2};const m=routes.filter(r=>String(r.route).toUpperCase().includes(q)).sort((a,b)=>(String(a.route).toUpperCase()===q?0:1)-(String(b.route).toUpperCase()===q?0:1)||rank[a.operator]-rank[b.operator]||String(a.route).localeCompare(String(b.route),undefined,{numeric:true})).slice(0,20);$("#searchResults").innerHTML=m.length?m.map(r=>`<button class="result-card"><div class="result-top"><span class="route">${esc(r.route)}</span><span class="operator">${opName(r.operator)}</span></div><div class="result-dest">${esc(r.orig)} → ${esc(r.dest)}</div></button>`).join(""):'<div class="muted">搵唔到相關路線。</div>'}
$("#openSearch").onclick=()=>{$("#searchSection").classList.toggle("hidden");$("#searchInput").focus()};$("#doSearch").onclick=doSearch;$("#searchInput").addEventListener("keydown",e=>{if(e.key==="Enter")doSearch()});$("#refreshBtn").onclick=renderFavs;$("#backBtn").onclick=()=>{$("#detailSection").classList.add("hidden");$("#favSection").classList.remove("hidden");$("#openSearch").classList.remove("hidden")};loadRoutes();renderFavs();setInterval(renderFavs,30000);
